apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testing
  name: testing
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels: {}

  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels: {}
    spec:
      containers:
        - command:
            - sleep
            - infinity
          image: ubuntu
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: envs
            - secretRef:
                name: secrets
          name: ubuntu
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
