apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-05-11T09:51:51Z"
  generation: 1
  labels:
    app: testing
  name: testing
  namespace: default
  resourceVersion: "121685225"
  uid: 3c65a250-d573-494e-a3e0-efef38a77dd8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels: {}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels: {}
    spec:
      containers:
        - command:
            - sleep
            - infinity
          image: ubuntu
          imagePullPolicy: Always
          name: ubuntu
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
