kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - deployment.yaml


configMapGenerator:
  - name: envs
    envs:
      - .env
secretGenerator:
  - name: secrets
    envs:
      - .secret.env