apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: testing
  name: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testing
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: testing
    spec:
      containers:
      - command:
        - sleep
        - infinity
        image: ubuntu
        name: ubuntu
        resources: {}
status: {}
